const FEATURES = [
  {
    icon: '⚡',
    title: 'Instant Vertical Feed',
    description:
      'Swipe up to the next episode like TikTok — but every video is a cinematic story with real plot tension.',
  },
  {
    icon: '🎬',
    title: 'AI-Produced Cinema',
    description:
      'Every episode is generated by a cutting-edge pipeline: GPT-4 scripts → Luma Dream Machine visuals → ElevenLabs voice acting.',
  },
  {
    icon: '🔒',
    title: 'Watch Free, Unlock More',
    description:
      'First two episodes of every series are free. Unlock the rest with coins earned from ads or via our subscription.',
  },
  {
    icon: '📶',
    title: 'Sub-Second Buffering',
    description:
      'HLS streaming from Cloudflare R2 ensures silky playback worldwide — no lag, no quality drops.',
  },
  {
    icon: '🌍',
    title: 'Multi-Language Voice',
    description:
      'Characters speak in English, Spanish, French, and more via ElevenLabs multilingual voice cloning.',
  },
  {
    icon: '📲',
    title: 'Direct APK — No Middleman',
    description:
      'Download directly from cinedrama.app. No app store approval wait, always on the latest build.',
  },
];

export default function Features() {
  return (
    <section id="features" className="py-24 px-6 bg-brand-card/30">
      <div className="mx-auto max-w-7xl">
        <div className="text-center mb-14">
          <p className="text-brand-red text-sm font-semibold uppercase tracking-widest mb-3">
            Platform Features
          </p>
          <h2 className="text-4xl md:text-5xl font-extrabold">
            Why CineDrama <span className="text-brand-red">Hits Different</span>
          </h2>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((f, i) => (
            <div
              key={i}
              className="group bg-brand-card border border-brand-border hover:border-brand-red/40 rounded-2xl p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:shadow-brand-red/5"
            >
              <div className="text-3xl mb-4">{f.icon}</div>
              <h3 className="text-white font-bold text-lg mb-2">{f.title}</h3>
              <p className="text-brand-muted text-sm leading-relaxed">
                {f.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
