/**
 * Media gateway — server-side proxy with HMAC authorization.
 *
 * GET /api/v1/media/play?episodeId=<uuid>&expires=<ts>&sig=<hmac>
 *
 * Flow:
 *  1. Validate HMAC + expiry (generated by signMediaUrl using SESSION_SECRET).
 *  2. Look up the raw CDN storage path from the database.
 *  3. Proxy the response from the CDN to the client — the raw origin URL is
 *     NEVER sent to the client, not even in a redirect Location header.
 *
 * Why proxy instead of redirect:
 *  A 302 sends the raw CDN URL in the Location header, allowing clients to
 *  bookmark it, share it, or request the CDN origin directly while bypassing
 *  entitlement checks. With a proxy, the client only ever communicates with
 *  this gateway, and the CDN origin can be kept private (VPC-only / IP-
 *  allowlisted to the gateway's egress).
 *
 * Range requests (video seeking) and HLS segments (.ts) are forwarded so
 * players can seek and stream without buffering the entire file.
 */

import { Router, Request, Response } from 'express';
import { db } from '@workspace/db';
import { episodesTable } from '@workspace/db';
import { eq } from 'drizzle-orm';
import { verifyMediaToken } from '../lib/signedUrl.js';
import { Readable } from 'stream';

export const mediaRouter = Router();

mediaRouter.get('/play', async (req: Request, res: Response) => {
  const { episodeId, expires: expiresStr, sig } = req.query as Record<string, string>;

  // ── 1. Validate query params ───────────────────────────────────────────────
  if (!episodeId || !expiresStr || !sig) {
    res.status(403).json({ error: 'Missing or invalid media token.' });
    return;
  }

  const expires = parseInt(expiresStr, 10);
  if (isNaN(expires)) {
    res.status(403).json({ error: 'Invalid token expiry.' });
    return;
  }

  // ── 2. Verify HMAC + expiry (constant-time) ────────────────────────────────
  if (!verifyMediaToken(episodeId, expires, sig)) {
    res.status(403).json({ error: 'Media token is invalid or has expired.' });
    return;
  }

  // ── 3. Look up the raw storage path (never exposed to clients) ─────────────
  let rawUrl: string | null = null;
  try {
    const [episode] = await db
      .select({ videoUrl: episodesTable.videoUrl })
      .from(episodesTable)
      .where(eq(episodesTable.id, episodeId))
      .limit(1);

    rawUrl = episode?.videoUrl ?? null;
  } catch (err) {
    req.log.error(err, 'Media gateway: DB lookup failed');
    res.status(500).json({ error: 'Internal server error' });
    return;
  }

  if (!rawUrl) {
    res.status(404).json({ error: 'Episode media not found.' });
    return;
  }

  // ── 4. Proxy response from CDN origin ─────────────────────────────────────
  //   - Forward Range header so players can seek and HLS segments work.
  //   - Stream body back to client without buffering.
  //   - CDN origin can be VPC-private; clients never learn its address.
  try {
    const upstreamHeaders: Record<string, string> = {};
    const rangeHeader = req.headers['range'];
    if (rangeHeader) {
      upstreamHeaders['Range'] = rangeHeader;
    }

    const upstream = await fetch(rawUrl, {
      headers: upstreamHeaders,
      // Abort if the CDN stalls for > 30 seconds
      signal: AbortSignal.timeout(30_000),
    });

    // Forward status (200 OK or 206 Partial Content for range requests)
    res.status(upstream.status);

    // Forward relevant headers (omit hop-by-hop and origin-revealing ones)
    const forward = [
      'content-type',
      'content-length',
      'content-range',
      'accept-ranges',
      'cache-control',
      'etag',
      'last-modified',
    ];
    for (const h of forward) {
      const val = upstream.headers.get(h);
      if (val) res.setHeader(h, val);
    }

    // Prevent clients from caching the raw URL via any injected header
    res.removeHeader('Location');

    if (!upstream.body) {
      res.end();
      return;
    }

    // Stream body through without buffering (supports large video files)
    Readable.fromWeb(upstream.body as import('stream/web').ReadableStream<Uint8Array>).pipe(res);
  } catch (err: any) {
    if (err?.name === 'TimeoutError' || err?.name === 'AbortError') {
      req.log.warn({ episodeId }, 'Media gateway: upstream CDN timed out');
      res.status(504).json({ error: 'Media origin timed out.' });
    } else if (err?.code === 'ENOTFOUND' || err?.code === 'ECONNREFUSED') {
      // Expected in development where cdn.cinedrama.app is a placeholder.
      // In production the CDN origin is a private, reachable host.
      req.log.warn({ episodeId, err: err.message }, 'Media gateway: CDN origin unreachable (placeholder)');
      res.status(502).json({ error: 'Media origin unreachable.' });
    } else {
      req.log.error(err, 'Media gateway: proxy error');
      res.status(502).json({ error: 'Failed to retrieve media.' });
    }
  }
});
