#!/usr/bin/env bash
#
# Provision PostgreSQL 16 on Ubuntu for CineDrama.
#
# Creates a dedicated database + user, generates a strong password,
# and writes the EnvironmentFile placeholder for the backend.
#
# Run as root on the VPS:
#   sudo bash deploy/scripts/provision-postgres.sh
#
# NEVER commit the generated secrets. This script writes them to
# /etc/cinedrama/backend.env (mode 0600, owned by the cinedrama user).
#
set -euo pipefail

DB_NAME="cinedrama"
DB_USER="cinedrama"
ENV_FILE="/etc/cinedrama/backend.env"
PG_HBA="/etc/postgresql/16/main/pg_hba.conf"
PG_CONF="/etc/postgresql/16/main/postgresql.conf"

echo "=== CineDrama PostgreSQL provisioning ==="

# --- 1. Install PostgreSQL 16 if not present ---
# Check for the server itself, not just the psql client binary.
# command -v psql false-positives when only postgresql-client is installed.
#
# On Ubuntu 24.04, the native postgresql-16 package is available in the
# default repo and is preferred over the PGDG repo. On Ubuntu 22.04 and
# earlier, we add the PGDG repo to get PostgreSQL 16.
if dpkg -s postgresql-16 &> /dev/null; then
  echo "[1/6] PostgreSQL 16 server already installed."
else
  echo "[1/6] Installing PostgreSQL 16..."
  apt-get update -qq
  apt-get install -y -qq curl ca-certificates gnupg

  # Try the native Ubuntu repo first (Ubuntu 24.04 ships postgresql-16)
  if apt-cache show postgresql-16 2>/dev/null | grep -q "Package: postgresql-16"; then
    echo "    Installing from native Ubuntu repo (Ubuntu 24.04+)"
    apt-get install -y -qq postgresql-16
  else
    echo "    Native package not found, adding PGDG repo (Ubuntu 22.04)"
    install -d /usr/share/postgresql-common/pgdg
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
      -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
      > /etc/apt/sources.list.d/pgdg.list
    apt-get update -qq
    apt-get install -y -qq postgresql-16
  fi
fi

# --- 2. Start the service ---
echo "[2/6] Ensuring PostgreSQL is running..."
systemctl enable --now postgresql

# --- 3. Create database + user with strong password ---
echo "[3/6] Creating database '${DB_NAME}' and user '${DB_USER}'..."
DB_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)

su - postgres -c "psql -v ON_ERROR_STOP=1" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASS}';
  ELSE
    ALTER ROLE ${DB_USER} WITH PASSWORD '${DB_PASS}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
SQL

# --- 4. Lock down listen address to localhost only ---
echo "[4/6] Configuring PostgreSQL to listen on localhost only..."
if grep -q "^#listen_addresses" "$PG_CONF" 2>/dev/null || ! grep -q "^listen_addresses" "$PG_CONF"; then
  sed -i "s/^#\?listen_addresses.*/listen_addresses = 'localhost'/" "$PG_CONF"
  systemctl restart postgresql
fi

# Ensure local auth uses scram-sha-256
if [ -f "$PG_HBA" ]; then
  if ! grep -q "scram-sha-256" "$PG_HBA"; then
    sed -i 's/^local\s\+all\s\+all\s\+peer/local   all             all                                     scram-sha-256/' "$PG_HBA"
    sed -i 's/^host\s\+all\s\+all\s\+127.0.0.1\/32\s\+\(md5\|scram-sha-256\)/host    all             all             127.0.0.1\/32            scram-sha-256/' "$PG_HBA"
    systemctl restart postgresql
  fi
fi

# --- 5. Generate JWT secret ---
echo "[5/6] Generating JWT secret..."
JWT_SECRET=$(openssl rand -base64 48)

# --- 6. Write EnvironmentFile ---
echo "[6/6] Writing ${ENV_FILE}..."
mkdir -p /etc/cinedrama

# Create the cinedrama system user if it does not exist
if ! id -u cinedrama &> /dev/null; then
  useradd --system --no-create-home --shell /usr/sbin/nologin cinedrama
fi

cat > "$ENV_FILE" <<EOF
# /etc/cinedrama/backend.env
# Generated by provision-postgres.sh
# Mode 0600, owned by cinedrama:cinedrama
# REVIEW AND ADJUST CORS_ORIGINS BEFORE STARTING THE SERVICE.

NODE_ENV=production
PORT=5000

DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}
JWT_SECRET=${JWT_SECRET}
CORS_ORIGINS=https://cinedrama.app
EOF

chown cinedrama:cinedrama "$ENV_FILE"
chmod 0600 "$ENV_FILE"

echo ""
echo "=== Provisioning complete ==="
echo "Database: ${DB_NAME}"
echo "User:     ${DB_USER}"
echo "Env file: ${ENV_FILE}"
echo ""
echo "WARNING: ${ENV_FILE} contains secrets. Do not copy or commit this file."
echo "Next steps:"
echo "  1. cd backend && npm ci && npm run build"
echo "  2. npm run db:push   (creates tables)"
echo "  3. npm run db:seed   (loads sample data)"
echo "  4. systemctl start cinedrama-api"
