#!/usr/bin/env bash
#
# Provision CineDrama Web (Next.js) on the VPS.
#
# Run as root on the VPS:
#   sudo bash deploy/scripts/provision-web.sh
#
# DOES NOT deploy application code. It creates:
#   - /opt/cinedrama/web            app directory
#   - /etc/cinedrama/web.env        runtime env file (mode 0600, cinedrama)
#   - /etc/systemd/system/cinedrama-web.service -> deploy/cinedrama-web.service
#   - enables cinedrama-web
#
# Build/deploy code separately with deploy/scripts/deploy-web.sh.
#
set -euo pipefail

API_BASE_URL="${API_BASE_URL:-https://api.cinedrama.app}"
APK_URL="${APK_URL:-https://cinedrama.app/download/cinedrama-latest.apk}"
APP_PATH="/opt/cinedrama/web"
ENV_FILE="/etc/cinedrama/web.env"
SERVICE_FILE="deploy/cinedrama-web.service"
SERVICE_DEST="/etc/systemd/system/cinedrama-web.service"
PORT="${PORT:-3000}"

echo "=== CineDrama Web provisioning ==="

# --- 1. Ensure system user exists ---
if ! id -u cinedrama &> /dev/null; then
  echo "[1/6] Creating cinedrama system user..."
  useradd --system --no-create-home --shell /usr/sbin/nologin cinedrama
else
  echo "[1/6] cinedrama user already exists."
fi

# --- 2. Ensure Node.js 20 is present ---
echo "[2/6] Checking Node.js..."
if ! command -v node >/dev/null 2>&1 || [ "$(node -p 'process.versions.node.split(".")[0]')" -lt 20 ]; then
  echo "    Node.js 20+ not found. Install Node 20 (e.g. nodesource/nvm) before continuing."
  exit 1
fi
echo "    Node $(node -v)"

# --- 3. Create app directory ---
echo "[3/6] Creating ${APP_PATH}..."
mkdir -p "${APP_PATH}"
chown -R cinedrama:cinedrama /opt/cinedrama

# --- 4. Create APK download directory ---
echo "[4/6] Creating /opt/cinedrama/downloads..."
mkdir -p /opt/cinedrama/downloads
chown -R cinedrama:cinedrama /opt/cinedrama/downloads

# --- 5. Write runtime env file ---
echo "[5/6] Writing ${ENV_FILE}..."
mkdir -p /etc/cinedrama
cat > "${ENV_FILE}" <<EOF
# /etc/cinedrama/web.env
# Generated by provision-web.sh
# Mode 0600, owned by cinedrama:cinedrama
NODE_ENV=production
PORT=${PORT}
NEXT_PUBLIC_APK_URL=${APK_URL}
NEXT_PUBLIC_API_BASE_URL=${API_BASE_URL}
EOF
chown cinedrama:cinedrama "${ENV_FILE}"
chmod 0600 "${ENV_FILE}"

# --- 6. Install systemd service ---
echo "[6/6] Installing cinedrama-web.service..."
if [ -f "${SERVICE_FILE}" ]; then
  install -m 0644 "${SERVICE_FILE}" "${SERVICE_DEST}"
else
  echo "    ERROR: ${SERVICE_FILE} not found (run from repo root)."
  exit 1
fi
systemctl daemon-reload
systemctl enable cinedrama-web

echo ""
echo "=== Provisioning complete ==="
echo "App dir:  ${APP_PATH}"
echo "Env file: ${ENV_FILE} (mode 0600)"
echo ""
echo "Next steps:"
echo "  1. bash deploy/scripts/deploy-web.sh   # builds + deploys code"
echo "  2. Copy the nginx vhost and run certbot (see deploy/web-vps-deploy.md)"
echo "  3. systemctl status cinedrama-web"
