#!/usr/bin/env bash
#
# Provision CineDrama Web (Next.js) on the VPS.
#
# Run as root on the VPS:
#   sudo bash deploy/scripts/provision-web.sh
#
# DOES NOT deploy application code. It creates:
#   - /opt/cinedrama/web                live app dir (systemd: cinedrama-web)
#   - /opt/cinedrama/web-deploy         staging dir for deploy-web.sh
#   - shared deploy group 'cinedramadeploy' with group-write on live+staging
#   - /etc/cinedrama/web.env            runtime env file (mode 0600, cinedrama)
#   - /etc/systemd/system/cinedrama-web.service
#   - scoped NOPASSWD sudoers rule for the deploy user (restart only)
#
# Ownership model (consistency requirement between provision + deploy):
#   - Service user `cinedrama` owns the files (uid cinedrama), group
#     cinedramadeploy.
#   - The SSH deploy user (WEB_DEPLOY_USER, default `deploy`) is a member of
#     cinedramadeploy, which has group write on live + staging. That lets it
#     build in staging and promote to live, while `cinedrama` only needs
#     read+execute to serve.
#   - The systemd service user must have nologin; never use it as the deploy
#     SSH user.
#
# Build/deploy code separately with deploy/scripts/deploy-web.sh (over SSH) or
# deploy/scripts/deploy-web-local.sh (run directly on the VPS).
#
set -euo pipefail

API_BASE_URL="${API_BASE_URL:-https://api.cinedrama.app}"
APK_URL="${APK_URL:-https://cinedrama.app/download/cinedrama-latest.apk}"
APP_PATH="/opt/cinedrama/web"
APP_STAGING="${APP_PATH}-deploy"
ENV_FILE="/etc/cinedrama/web.env"
SERVICE_FILE="deploy/cinedrama-web.service"
SERVICE_DEST="/etc/systemd/system/cinedrama-web.service"
PORT="${PORT:-3000}"
DEPLOY_GROUP="cinedramadeploy"
WEB_DEPLOY_USER="${WEB_DEPLOY_USER:-deploy}"
SUDOERS_FILE="/etc/sudoers.d/cinedrama-web"

# Guard: the deploy SSH user must be an interactive/SSH-capable username, never
# the nologin service account.
if [ "${WEB_DEPLOY_USER}" = "cinedrama" ]; then
  echo "ERROR: WEB_DEPLOY_USER cannot be 'cinedrama' (it is the nologin service user)."
  echo "       Set WEB_DEPLOY_USER to a real SSH account, e.g. deploy."
  exit 1
fi

echo "=== CineDrama Web provisioning ==="
echo "  deploy user: ${WEB_DEPLOY_USER}"
echo "  group:       ${DEPLOY_GROUP}"

# --- 1. Ensure service user exists ---
if ! id -u cinedrama &> /dev/null; then
  echo "[1/8] Creating cinedrama service user..."
  useradd --system --no-create-home --shell /usr/sbin/nologin cinedrama
else
  echo "[1/8] cinedrama user already exists."
fi

# --- 2. Ensure Node.js 20 is present (install via NodeSource on clean boxes) ---
echo "[2/8] Ensuring Node.js 20..."
if ! command -v node >/dev/null 2>&1 || [ "$(node -p 'process.versions.node.split(".")[0]')" -lt 20 ]; then
  echo "    Node.js 20+ not found. Installing Node 20 via NodeSource..."
  apt-get update -qq
  apt-get install -y -qq curl ca-certificates gnupg rsync
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y -qq nodejs
fi
# rsync is used by the local deploy script; ensure it exists regardless.
command -v rsync >/dev/null 2>&1 || apt-get install -y -qq rsync
echo "    Node $(node -v)"

# --- 3. Shared deploy group + app/staging directories ---
echo "[3/8] Creating shared deploy group '${DEPLOY_GROUP}' + dirs..."
if ! getent group "${DEPLOY_GROUP}" >/dev/null 2>&1; then
  groupadd --system "${DEPLOY_GROUP}"
fi
# Ensure service user is in the shared group.
if ! id -nG cinedrama | tr ' ' '\n' | grep -qx "${DEPLOY_GROUP}"; then
  usermod -aG "${DEPLOY_GROUP}" cinedrama
fi
# Create the SSH deploy user if it does not exist (home + bash so it can SSH).
if ! id -u "${WEB_DEPLOY_USER}" &> /dev/null; then
  echo "    Creating deploy user '${WEB_DEPLOY_USER}' (home + bash)..."
  useradd --create-home --shell /bin/bash "${WEB_DEPLOY_USER}"
fi
if ! id -nG "${WEB_DEPLOY_USER}" | tr ' ' '\n' | grep -qx "${DEPLOY_GROUP}"; then
  usermod -aG "${DEPLOY_GROUP}" "${WEB_DEPLOY_USER}"
fi

mkdir -p "${APP_PATH}" "${APP_STAGING}"
# cinedrama owns the files; group is cinedramadeploy with write so the deploy
# user (same group) can build/promote. The service user only needs read+exec.
chown -R "cinedrama:${DEPLOY_GROUP}" "${APP_PATH}" "${APP_STAGING}"
chmod -R "g+rwX" "${APP_PATH}" "${APP_STAGING}"
# setgid on directories: new files/dirs inherit the cinedramadeploy group.
find "${APP_PATH}" "${APP_STAGING}" -type d -exec chmod g+s {} \;

# --- 4. APK download + previews directories ---
echo "[4/8] Creating /opt/cinedrama/downloads and previews (readable by nginx)..."
mkdir -p /opt/cinedrama/downloads /opt/cinedrama/downloads/previews
chown -R cinedrama:cinedrama /opt/cinedrama/downloads
find /opt/cinedrama/downloads -type d -exec chmod 755 {} \;

# --- 5. Write runtime env file ---
echo "[5/8] Writing ${ENV_FILE}..."
mkdir -p /etc/cinedrama
cat > "${ENV_FILE}" <<EOF
# /etc/cinedrama/web.env
# Generated by provision-web.sh
# Mode 0600, owned by cinedrama:cinedrama
NODE_ENV=production
PORT=${PORT}
NEXT_PUBLIC_APK_URL=${APK_URL}
NEXT_PUBLIC_API_BASE_URL=${API_BASE_URL}
EOF
chown cinedrama:cinedrama "${ENV_FILE}"
chmod 0600 "${ENV_FILE}"

# --- 6. Install systemd service ---
echo "[6/8] Installing cinedrama-web.service..."
if [ -f "${SERVICE_FILE}" ]; then
  install -m 0644 "${SERVICE_FILE}" "${SERVICE_DEST}"
else
  echo "    ERROR: ${SERVICE_FILE} not found (run from repo root)."
  exit 1
fi
systemctl daemon-reload
systemctl enable cinedrama-web

# --- 7. Scoped sudoers (restart ONLY; exact command match) ---
echo "[7/8] Installing scoped sudoers for ${WEB_DEPLOY_USER}..."
cat > "${SUDOERS_FILE}" <<EOF
# CineDrama web deploy — scoped to EXACTLY the restart command used by
# deploy-web.sh. Status/is-active is unprivileged, so no sudo is needed there.
# Installed by provision-web.sh. Do NOT broaden.
${WEB_DEPLOY_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart cinedrama-web
EOF
chmod 0440 "${SUDOERS_FILE}"
if visudo -cf "${SUDOERS_FILE}" >/dev/null 2>&1; then
  echo "    sudoers rule valid for ${WEB_DEPLOY_USER}."
else
  echo "    ERROR: sudoers validation failed for ${SUDOERS_FILE}."
  exit 1
fi

# --- 8. Summary ---
echo "[8/8] Done."

echo ""
echo "=== Provisioning complete ==="
echo "App dir:    ${APP_PATH}"
echo "Staging:    ${APP_STAGING}"
echo "Env file:   ${ENV_FILE} (mode 0600)"
echo "Group:      ${DEPLOY_GROUP} (cinedrama + ${WEB_DEPLOY_USER})"
echo "Deploy user: ${WEB_DEPLOY_USER} (must match WEB_DEPLOY_USER in deploy-web.sh)"
echo ""
echo "Next steps:"
echo "  1. Install the deploy public key into ${WEB_DEPLOY_USER}'s authorized_keys"
echo "  2. bash deploy/scripts/deploy-web.sh   # builds + deploys code"
echo "  3. Copy the nginx vhost and run certbot (see deploy/web-vps-deploy.md)"
echo "  4. systemctl is-active cinedrama-web"
